---
- name: Create chart path
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    
- name: Copy Flux helm chart
  template:
    src: ../templates/flux-staging.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/flux-staging.yaml