- name: Remove iptables persitent
  apt:
    name:
    - iptables-persitent
    - netfilter-persistent
    state: absent

#Shell Command is faster than module
- name: Iptables flush filter
  shell: iptables -F && iptables -t nat -F
